import { createOsmProvider } from './server/osmProvider.js'
const osm = createOsmProvider({ timeoutMs: 20000 })
const search = await osm.searchPlaces({ query: 'Toit Bengaluru', limit: 5 })
console.log('search address:', JSON.stringify(search.results[0].address).slice(0, 160))
const url = new URL('https://nominatim.openstreetmap.org/reverse')
url.searchParams.set('lat', '12.9794113')
url.searchParams.set('lon', '77.6406278')
url.searchParams.set('format', 'jsonv2')
console.log('url:', url.toString())
const res = await fetch(url, { headers: { 'User-Agent': 'CrowdTaste/1.0 (restaurant discovery demo; local development use)' } })
const j = await res.json()
console.log('status:', res.status, '| display_name len:', (j.display_name || '').length)
const detail = await osm.getPlace('node', '1923665125')
console.log('detail address len:', detail.address.length, '| start:', detail.address.slice(0, 100))
